export const INITIAL_NOTE_VALUES =
  // C major scale
  [60, 62, 64, 65, 67, 69, 71, 72];

export const NOTE_OPTIONS = [
  { name: " ", midi: 0 },
  { name: "A1", midi: 33 },
  { name: "A#1", midi: 34 },
  { name: "B1", midi: 35 },
  { name: "C1", midi: 36 },
  { name: "C#1", midi: 37 },
  { name: "D1", midi: 38 },
  { name: "D#1", midi: 39 },
  { name: "E1", midi: 40 },
  { name: "F1", midi: 41 },
  { name: "F#1", midi: 42 },
  { name: "C2", midi: 36 },
  { name: "C#2", midi: 37 },
  { name: "D2", midi: 38 },
  { name: "D#2", midi: 39 },
  { name: "E2", midi: 40 },
  { name: "F2", midi: 41 },
  { name: "F#2", midi: 42 },
  { name: "G2", midi: 43 },
  { name: "G#2", midi: 44 },
  { name: "A2", midi: 45 },
  { name: "A#2", midi: 46 },
  { name: "B2", midi: 47 },
  { name: "C3", midi: 48 },
  { name: "C#3", midi: 49 },
  { name: "D3", midi: 50 },
  { name: "D#3", midi: 51 },
  { name: "E3", midi: 52 },
  { name: "F3", midi: 53 },
  { name: "F#3", midi: 54 },
  { name: "G3", midi: 55 },
  { name: "G#3", midi: 56 },
  { name: "A3", midi: 57 },
  { name: "A#3", midi: 58 },
  { name: "B3", midi: 59 },
  { name: "C4", midi: 60 },
  { name: "C#4", midi: 61 },
  { name: "D4", midi: 62 },
  { name: "D#4", midi: 63 },
  { name: "E4", midi: 64 },
  { name: "F4", midi: 65 },
  { name: "F#4", midi: 66 },
  { name: "G4", midi: 67 },
  { name: "G#4", midi: 68 },
  { name: "A4", midi: 69 },
  { name: "A#4", midi: 70 },
  { name: "B4", midi: 71 },
  { name: "C5", midi: 72 },
];

export const ARTIST_LOCAL_STORAGE_KEY = "artist";
export const TITLE_LOCAL_STORAGE_KEY = "title";
